openapi: 3.0.1
info:
  title: Nut Butter e-Commerce API
  version: 1.0.0
  description: An API for a fictional nut butter e-commerce store
paths:
  /auth/customer:
    summary: Create a new customer account
    description: 'This path is used to authorise a new customer''s account '
    post:
      summary: Create new customer account
      description: >-
        User inputs the required information and this is added to create a new
        customer account
      operationId: new_customer
      responses:
        default:
          description: Default error sample response
      tags:
        - Auth
  /auth/{customer_id}/login:
    summary: This path is used to log in to a customer's account
    post:
      summary: Log in to a customer's account
      description: Authenticates a user's credentials to log them in to their account
      operationId: customer_login
      responses:
        default:
          description: Default error sample response
      tags:
        - Auth
  /auth/{customer_id}/logout:
    summary: This path is used to log out of a customer's account
    post:
      summary: Log out of a customer's account
      description: Ends the customer's current session and logs them out of their account
      operationId: customer_logout
      responses:
        default:
          description: Default error sample response
      tags:
        - Auth
  /customers:
    summary: Retrieves all customer's data
    description: This path is used to retrieve all customer data
    get:
      summary: Retrieve all customers
      description: This path retrieves all customer information for all existing customers
      operationId: all_customers
      responses:
        default:
          description: Default error sample response
      tags:
        - Customers
  /customers/{id}:
    summary: Actions on an individual customer account
    description: Used to retrieve, edit and delete a specific customer's account by id
    get:
      summary: Retrieve one customer by id
      description: This path retrieves the details of one specific customer by id
      operationId: get_customer
      responses:
        default:
          description: Default error sample response
      tags:
          - Customers
    patch:
      summary: Edit existing customer by id
      description: 'This path updates the details of a customer '
      operationId: edit_customer
      responses:
        default:
          description: Default error sample response
      tags:
          - Customers
    delete:
      summary: Delete a customer by id
      description: This path deletes a customer's account
      operationId: delete_customer
      responses:
        default:
          description: Default error sample response
      tags:
          - Customers
  /addresses:
    summary: Retrieve all customer addresses
    description: This path will pull all of the addresses for all registered customers
    get:
      summary: Retrieve all customer addresses
      description: This path will pull all of the addresses registered by customers
      operationId: get_addresses
      responses:
        default:
          description: Default error sample response
      tags:
          - Addresses
  /addresses/{customer_id}:
    summary: Retrieve a specific customer's address(es)
    description: This path pulls a customer's address(es) associated with their customer id
    get:
      summary: Retrieve all addresses registered to one customer's account
      description: This path fetches all of the addresses associated to one user's account
      operationId: customer_addresses
      responses:
        default:
          description: Default error sample response
      tags:
          - Addresses
  /addresses/{customer_id}/{address_id}:
    summary: Actions on a specific customer's address
    description: >-
      Used to retrieve, edit and delete a specific customer's account by
      customer_id and address_id
    post:
      summary: Create new address
      description: This path will add a new address for a customer
      operationId: new_address
      responses:
        default:
          description: Default error sample response
      tags:
          - Addresses
    put:
      summary: Edit existing customer address
      description: This path allows a user to update their address
      operationId: edit_address
      responses:
        default:
          description: Default error sample response
      tags:
          - Addresses
    delete:
      summary: Delete existing customer address
      description: This path will remove an existing address by address id
      operationId: delete_address
      responses:
        default:
          description: Default error sample response
      tags:
          - Addresses
  /products:
    summary: Retrieves all products
    description: This path is used to list all products available in the app
    get:
      summary: Retrieve all products
      description: This path fetches a list of all available products
      operationId: all_products
      responses:
        default:
          description: Default error sample response
      tags:
          - Addresses
  /products/{product_id}:
    summary: Actions on an individual product
    description: Used to retrieve, edit and delete a specific product by id
    get:
      summary: Retrieve a specific product
      description: Return a specific product by id
      operationId: find_product
      responses:
        default:
          description: Default error sample response
      tags:
          - Products
    post:
      summary: Add a new product to the store
      description: This path will create a new product and add it to the store
      operationId: new_product
      responses:
        default:
          description: Default error sample response
      tags:
          - Products
    put:
      summary: Update an existing product
      description: Updates the information relating to a specific product id
      operationId: update_product
      responses:
        default:
          description: Default error sample response
      tags:
          - Products
    delete:
      summary: Deletes an existing product
      description: This path will remove a product from the store
      operationId: delete_product
      responses:
        default:
          description: Default error sample response
      tags:
          - Products
  /cart/{customer_id}:
    summary: Creates a new cart for a customer
    description: Starts a new cart specific to customer id
    post:
      summary: Creates a new cart for the customer
      description: This path will create a new path specific to the customer id
      operationId: new_cart
      responses:
        default:
          description: Default error sample response
      tags:
          - Carts
  /cart/{customer_id}/{cart_id}/{product_id}:
    summary: Actions on a specific product within a customer's cart
    description: Used to add, edit and remove items from a customer's cart
    post:
      summary: Add a product to the customer's cart
      description: Add a specific product id to a customer's current cart
      operationId: cart_add_item
      responses:
        default:
          description: Default error sample response
      tags:
          - Carts
    put:
      summary: Adds additional quantity of an existing product in a customer's card
      description: Increments the quantity of a product by id in a customer's cart
      operationId: cart_update_item
      responses:
        default:
          description: Default error sample response
      tags:
          - Carts
    delete:
      summary: Remove a specific product from the customer's cart
      description: This path will delete a product by id from a customer's cart
      operationId: cart_delete_item
      responses:
        default:
          description: Default error sample response
      tags:
          - Carts
  /cart/{customer_id}/{cart_id}:
    summary: Actions on a customer's current cart
    description: Used to retrieve and delete all items from a customer's account
    delete:
      summary: 'Delete/empty a customer''s cart '
      description: >-
        This path will remove all products from a customer's cart and delete the
        cart
      operationId: delete_cart
      responses:
        default:
          description: Default error sample response
      tags:
          - Carts
    get:
      summary: Retrieve a customer's cart
      description: This path will retrieve an existing cart by id
      operationId: get_cart
      responses:
        default:
          description: Default error sample response
      tags:
          - Carts
  /orders/{customer_id}:
    summary: Interact with a customer's orders
    description: This path is used to add new orders and retrieve existing orders
    post:
      summary: 'Add a new order '
      description: This path will add a new order placed by a customer
      operationId: new_order
      responses:
        default:
          description: Default error sample response
      tags:
          - Orders
    get:
      summary: Retrieve all orders by customer id
      description: This path will find all past orders placed by a customer
      operationId: all_orders
      responses:
        default:
          description: Default error sample response
      tags:
          - Orders
  /orders/{customer_id}/{order_id}:
    summary: Retrieves a specific order
    description: 'This path retrieves an individual order '
    get:
      summary: Retrieve a specific order made by a customer
      description: This path will fetch a specific order from the customer's order history
      operationId: get_order
      responses:
        default:
          description: Default error sample response
      tags:
          - Orders
